MACOSX_SDK_VERSION:
  - '15.0'                   # [osx]

MACOSX_DEPLOYMENT_TARGET:
  - '15.0'                   # [osx]  

c_compiler:
 - vs2019                     # [win]
 - clang_bootstrap            # [osx]
 
cxx_compiler:
 - vs2019                     # [win]
 - clang_bootstrap            # [osx]

cxx_compiler_version:
 - 9.3.0                     # [linux]

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.12                       # [linux and x86_64]
  - 2.17                       # [linux and not x86_64]
  - 10.9                       # [osx and x86_64]
  - 11.0                       # [osx and arm64]